#!/usr/bin/env bash
# Installing nginx web server

sudo apt update
sudo apt install -y nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 's/listen 80 default_server;/listen 80;/g' | sudo tee /etc/www/html/sites-available/default

sudo service nginx reload
