#!/usr/bin/env bash
# Installing nginx web server

sudo apt update
sudo apt install -y nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo printf '%s\n' "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
}
" | sudo tee /etc/www/html/sites-available/default > /dev/null

sudo service nginx reload
