#!/usr/bin/env bash
# Installing nginx web server

sudo apt-get update
sudo apt install -y nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '\#root /var/www/html;#a\\tlocation /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx reload
