#!/usr/bin/env bash

sudo apt-get update
sudo apt -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf '%s\n' "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html{
                internal;
        }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx reload