#!/usr/bin/env bash
# Configures web-02 to be identical to web-01

sudo apt-get update
sudo apt -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee www/html/index.html

echo "This is not a page" | sudo tee www/html/404.html

printf '%s\n' "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	add_header X-Served-By '\$(hostname)';

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location /redirect_me {
		return 301 https://youtu.be/dQw4w9WgXcQ?si=X0uwfR31n77_wwWI
	}

	error_page 404 /404.html;
	location = /404.html {
		internal;
	};
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx reload
