#!/usr/bin/env bash
# Update package list

sudo apt-get update
sudo apt install -y haproxy

sudo service haproxy start

printf '%s\n' "frontend web
        bind *:80
        default_backend my_backend_servers

backend my_backend_servers
        balance roundrobin
        server 309253-web-01 100.25.131.49:80
        server 309253-web-02 52.3.250.251:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy reload
