#!/usr/bin/env bash
# This script displays the content of file /etc/passwd
# Your script should only display
# 	username
# 	user id
# 	Home directry path for the user

while read -r line; do
	echo "$line" | cut -d ":" -f 1,3,6
done</etc/passwd
