#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "Hi" on the 9th loop
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	i=$((i+1))
	if [ $i -eq 10 ]
	then
		echo "Hi"
	fi
done
