#!/usr/bin/env bash
# This script prints "bad luck" on the 4th loop,
# "good luck" on the 8th loop and
# "Best school" on the other loops
i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
