#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Where only part of the name after the firs dash is diplayed.

for i in *; do
	echo "$i" | cut -d "-" -f 2
done
