#!/usr/bin/env bash
# This script gives information about the school file
s="$(ls school)"
if [ -e "$s" ]; then
	echo "school file exists"
	if [ -s "$s" ]; then
		echo "school file is not empty"
	elif [ ! -s "$s" ]; then
		echo "school file is empty"
	elif [ -f "$s" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
