#!/usr/bin/env bash
# Configures an Ubuntu server
sudo cp /etc/hosts ~/hosts.new && sudo sed -i "s/127.0.0.1/127.0.0.1/g" ~/hosts.new && sudo cp -f ~/hosts.new /etc/hosts && rm -r ~/hosts.new
echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts > /dev/null

